### ISSUE TITLE
Erro ao Ativar Plugin

### ISSUE THREAD

**Issue by gabrielzagomarino** [gerencianet/gn-api-woocommerce#1]
Bom Dia,

Ao tentar ativar o plugin me deparei com um erro no arquivo:
woo-gerencianet-oficial/includes/lib/GerencianetIntegration.php, mais precisamente na linha 69

$max_installments = end($installments['data']['installments'])['installment'] . "x de " . GerencianetIntegration::formatCurrencyBRL(end($installments['data']['installments'])['value']);

**Comment by jpferreira123** [comment]
Bom dia @gabrielzagomarino ,

Qual foi a mensagem descritiva do erro apresentado para você? Você realizou a instalação do plugin através dos arquivos disponibilizados pelo GitHub ou pelo repositório oficial do WordPress? E qual a versão do PHP instalado no servidor em que está sua loja virtual?

Caso tenha interesse, adicione no skype: joao.ferreira.gerencianet

Aguardo seu retorno.

**Comment by gabrielzagomarino** [comment]
Boa Tarde @jpferreira123,
Te adicionei no skype para te mostrar os erros e o que você solicitou.

Abraço!

**Comment by gabrielzagomarino** [comment]
Boa Tarde @jpferreira123 

Segue o erro:
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /home/storage/7/97/10/ligsi2/public_html/v2/wp-content/plugins/woo-gerencianet-oficial/includes/lib/GerencianetIntegration.php on line 7

Estou realizando a instalação do plugin através dos arquivos do GitHub.

PHP version 5.2.17
Wordpress versão 4.4.3

Espero ter contribuído.

Abraço!

**Comment by jpferreira123** [comment]
Boa tarde @gabrielzagomarino 

O plugin da Gerencianet para WooCommerce é compatível somente com versões do PHP igual ou superior à 5.4.0, conforme informado nas instruções de configuração.
