### ISSUE TITLE
Problema com o PIX

### ISSUE THREAD

**Issue by paulodbs** [gerencianet/gn-api-woocommerce#10]
O Plugin está com problema na atualização automática do pedido feito pelo PIX, E está faltando a opção de copiar é colar o código PIX, e tem algumas coisas que está em Inglês.

**Comment by jvoliveiraGN** [comment]
Oi @paulodbs tudo bem?
Para que a gente possa replicar a falha, por favor nos informe qual ambiente está sendo realizada a emissão e se está utilizando validação MTLS.
O plugin está passando por algumas atualizações com melhorias e correções.
A inclusão do botão de copiar o Pix deve ser disponibilizada hoje até a tarde.
Acredito que com a nova atualização, os textos em inglês devem se corrigir também.

**Comment by jvoliveiraGN** [comment]
@paulodbs Obrigado pelo feedback!
Vamos avaliar como podemos resolver essa questão da compatibilidade e assim que tivermos novidades publicaremos aqui!
Aliás, caso você tenha experiência com WooCommerce e tenha alguma sugestão para contribuir com essa correção, será muito bem vindo! Toda ajuda já agiliza o processo!

Quaisquer dúvidas, estamos à disposição! 😄

**Comment by jvoliveiraGN** [comment]
Issue fechada por se tratar de uma falha da emissão de cobranças via Pix, que foi solucionada em uma atualização passada.
Será aberta uma nova issue para tratar da compatibilidade com o plugin Brazilian Market on WooCommerce 
Link: [Issue Brazilian Market on WooCommerce ](https://github.com/gerencianet/gn-api-woocommerce/issues/15)
