### ISSUE TITLE
Erros Internal Server Error e jQuery

### ISSUE THREAD

**Issue by marcos-alexandre82** [gerencianet/gn-api-woocommerce#14]
@jvoliveiraGN testei aqui o plugin e ele está dando erro no console:
https://prnt.sc/10ifmgx

https://prnt.sc/10ifmpu

Se eu comento a função "applyPhoneMask" do arquivo transparent-osc.php e limpo todos os campos do checkout, preencho novamente, ele até deixa avançar, mas colocando um CPF para finalizar o pagamento, ele da erro "Internal Server Error" como resposta.

Consegue verificar?

Estou usando WordPress (5.7), o tema Avada (7.2.1) e, dentre os plugins instalados, estão os plugins Brazilian Market on WooCommerce (3.7.2), WooCommerce (5.1.0), além do PHP 7.4.10, caso isso já ajude na investigação ;)

**Comment by jvoliveiraGN** [comment]
Oi @marcos-alexandre82 tudo bem? 👍 
Encontramos uma incompatibilidade ocorrendo com o plugin Brazilian Market on WooCommerce, inclusive relatado por outros usuários.
Essa demanda foi mapeada e será tratada na issue #15 
Quaisquer novidades atualizaremos aqui! :)

**Comment by jvoliveiraGN** [comment]
@marcos-alexandre82 Estamos efetuando alguns testes, e não conseguimos replicar essa falha!
Poderia nos dar mais detalhes na issue #15 ?
