### ISSUE TITLE
Tela de Pagamento

### ISSUE THREAD

**Issue by gabrielzagomarino** [gerencianet/gn-api-woocommerce#2]
Boa Tarde,

Tenho uma dúvida na tela de pagamento:
Deixei desmarcada a opção "Habilitar Checkout em uma Página", presumindo que o pagamento seria realizado em uma tela separada do Gerencianet. Fato que não ocorreu, a tela de pagamento com opção de Cartão de Crédito (dados para inserir) e Boleto está carregando na mesma página do site que está com o plugin instalado. Isso está ocorrendo pois estou utilizando certificado SSL em meu site? Ou ele irá carregar independente do procolo essas informações para o usuário digitar?
Para aqueles websites que não possuem certificado SSL instalado, essas informações de pagamento não ficariam vulneráveis no quesito segurança?

Fico no aguardo.
Obrigado.

Att,
Gabriel Zago

**Comment by jpferreira123** [comment]
Bom dia @gabrielzagomarino ,

O plugin da Gerencianet para WooCommerce funciona com o Checkout Transparente, ou seja, o cliente não irá sair da loja para realizar o pagamento em nenhum momento.
Nas configurações do plugin, o lojista pode optar pelo **Checkout Padrão** ou pelo **Checkout em uma Página**. No **Checkout Padrão**, o fluxo de compra se dará da seguinte forma: _Compra > Carrinho > Finalizar Compra > Realizar Pagamento > Pedido Finalizado_. O processo de _Realizar Pagamento_ será realizado em uma página diferente do _Finalizar Compra_. No **Checkout em uma página**, o fluxo será da seguinte forma: _Compra > Carrinho > Finalizar Compra > Pedido Finalizado_. Ou seja, o cliente irá inserir dos dados de pagamento na mesma tela de _Finalizar Compra_, logo haverá um passo a menos que no modo de Checkout Padrão. Essa será a única diferença entre os dois modos. O plugin funcionará da mesma forma, independente de utilizar o certificado SSL ou não.

Sobre o certificado SSL, é extremamente recomendado pela Gerencianet que os lojistas utilizem. Independente da sua utilização ou não, todos os dados de pagamento são criptografados e transmitidos com segurança para validação do pagamento. Contudo, a presença de um certificado SSL instalado em sua loja, garante maior segurança para o lojista e para os clientes que realizam  compras. A ausência do certificado SSL na tela de pagamento, pode fazer com que o lojista perca vendas, uma vez que o cliente pode se sentir inseguro para digitar dados de pagamento em uma página que não possui um certificado.

Caso não tenha entendido algum dos pontos, estou à disposição.

**Comment by gabrielzagomarino** [comment]
Entendido @jpferreira123 

Estou fazendo os teste e a princípio está funcionando perfeitamente.

Obrigado pelo esclarecimento.

Abraço!
