### ISSUE TITLE
Limitar Parcelas e Valor Mínimo

### ISSUE THREAD

**Issue by soraiareis** [gerencianet/gn-api-woocommerce#3]
Eu gostei bastante do plugin, mas gostaria de sugerir 2 implementações que ajudariam muito.

- Possibilidade de configurar número máximo de parcelas;
- Possibilidade de configurar valor mínimo de cada parcela.

Eu gostaria de limitar o pagamento do meu cliente a até 6 parcelas. Além disso, seria interessante colocar um mínimo da parcela de R$ 50,00.

Exemplo: Se o cliente comprar R$ 200,00 reais ele poderia parcelar em no máximo 4 vezes. E se o cliente comparar R$ 400,00 ele pode pagar em no máximo 6 vezes (mesmo que com a parcela mínima de R$ 50,00 ele pudesse pagar em 8x).

Há uma forma simples de alterar o plugin para que isso aconteça?

Uma melhoria também seria apresentar no texto do campos "Quantidade de parcelas" uma observação quando não tem juros "1x R$ 200,00 (sem juros)" e quando tem juros "2x de R$102,00 (com juros)".

**Comment by jvoliveiraGN** [comment]
Oi @soraiareis tudo bem? :)
Demanda mapeada para discussão, ainda sem previsão de implementação.
Obrigado pelo feedback! 👍
