### ISSUE TITLE
Ao Gerar o PIX está dando um erro

### ISSUE THREAD

**Issue by juizmill** [gerencianet/gn-api-woocommerce#35]
Ao realizar a solicitação de pagamento com PIX está gerando um erro.. 

![image](https://user-images.githubusercontent.com/1959742/139758022-b01a96c9-afc5-4bc4-897a-6179f613da1f.png)

**Comment by jvoliveiraGN** [comment]
Olá @juizmill Tudo bem? Esperamos que sim!
Primeiramente, gostaríamos de agradecer ao seu feedback!
Liberamos uma atualização ( #37 ) com algumas melhorias e correções, incluindo a mencionada acima!
Por favor, atualize a versão do seu plugin e verifique se a mensagem persiste.
Quaisquer dúvidas, conte com a gente!
