### ISSUE TITLE
Integração dos modulos pix, boleto e cartão deveria ser separada no woocommerce

### ISSUE THREAD

**Issue by JeffersonMatos** [gerencianet/gn-api-woocommerce#38]
A integração dos modulos pix, boleto e cartão deveria ser separada no woocommerce, que é o certo pra poder ter interação com outros plugins e com o próprio cupom do woo.
Da forma que tá não permite dar cupom de desconto pra um meio de pagamento especifico e não tem flexibilidade pra gerenciar os tipos de pagamento.
Tem um bug que não atualiza o valor no botão do woo quando seleciona o pix ou boleto com desconto
![checkoutgn](https://user-images.githubusercontent.com/5893510/164759296-29e0b1cf-3cc6-4701-8773-9b863e7eb368.jpg)
.
Quero indicar a todos clientes o gerencianet, mas assim fica difícil. A ux tá péssima. Só em separar os tipos de pagamento diretamente pelo woocommerce já resolve grande parte desses problemas.

**Comment by jvoliveiraGN** [comment]
Boa noite @JeffersonMatos tudo certo?
Acabamos de disponibilizar uma nova versão em que os métodos de pagamento estão separados!
Vale a pena dar uma conferida! Lembrando que nessa última atualização é necessário refazer as configurações do plugin, ok?

Obrigado pelo feedback!
Quaisquer dúvidas, estamos à disposição!
