### ISSUE TITLE
Bug versão 2+

### ISSUE THREAD

**Issue by gspsites** [gerencianet/gn-api-woocommerce#39]
o plugin a partir da versão 2 não deixa o usuário digitar o cpf no site, fiquei 4 dias sem vendas até achar o erro, só funciona na versão anterior

**Comment by jvoliveiraGN** [comment]
Bom dia @gspsites tudo certo?
Disponibilizamos a versão 2.0.4 do plugin Gerencianet Oficial, com algumas melhorias e correções.
Incluindo a correção dessa falha ao digitar CPF/CNPJ.
Caso surjam novas situações nessa nova versão, basta nos informar para verificarmos o ocorrido.
