### ISSUE TITLE
erro na mascara do CPF continua com problema no 0.63

### ISSUE THREAD

**Issue by YammYcoding** [gerencianet/gn-api-woocommerce#4]
Oi.
Estou na ultima versao do wordpress, woocommerce e seu plugin.

Mas continua dando erro na mascara do CPF. Ele nao deixa digitar outro numero alem do 000.000.000/0000-00

**Comment by tiagoxpl** [comment]
@YammYcoding 

Você pode utilizar o plugin "[WooCommerce Extra Checkout Fields for Brazil](http://wordpress.org/plugins/woocommerce-extra-checkout-fields-for-brazil/)", perceberá que o problema não irá mais ocorrer.

Qualquer questão, estamos à disposição.

**Comment by YammYcoding** [comment]
Achei o problema.  Faltava o plugin WooCommerce Extra Checkout Fields for Brazil
