### ISSUE TITLE
ERRO DE PHONE NUMBER INESISTENTE NA REQUISIÇÂO CONSERTAR URGENTE!! MUITO OBRIGADO

### ISSUE THREAD

**Issue by josearthur** [gerencianet/gn-api-woocommerce#43]
![image](https://user-images.githubusercontent.com/6089458/220816114-108b5f80-7ad5-48cb-9835-91ff49a0e776.png)
 Ja avisei este erro no atendimento de vocês que foi extremamente prestativo porem esta ocorrendo algum erro de comunicação por parte de vcs. Ja perdi mais de 20 vendas este carnaval porque estava rodando ads e o plugin foi atualizado. tenho outro sistema utilizando o sistema de vcs que este eu que desenvolvo então nao estou tendo problemas... mas isso me da um pouco de medo...

Em resumo o erro é que nao é enviado phone number para o sistema;

2
3
4
5
6
7
8
{
  "code": 3500034,
  "error": "validation_error",
  "error_description": {
    "property": "/payment/credit_card/customer/phone_number",
    "message": "A string não corresponde ao modelo: ^[1-9]{2}9?[0-9]{8}$."
  }
}
{
  "code": 3500034,
  "error": "validation_error",
  "error_description": {
    "property": "/payment/credit_card/customer/phone_number",
    "message": "A string não corresponde ao modelo: ^[1-9]{2}9?[0-9]{8}$."
  }
}

inclusive não tem tratamento para este tipo de resposta.. ao menos se retornasse um erro de campo invalido ou inexistente para facilitar o cliente a identificar o problema. 

 Tentei adicionar o Brasilian Market para ver se arrumava ja que o cellphone por padrao no woocomernce nao existe.e nao funcionou...

na versão 1.4 que funciona o celular vem dentro da caixa do plugin da gerencianet... pode ser resolvido da mesma forma...  espero ter esclarecido a situação. tenho muito respeito pela equipe de vocês... entendam a critica construtiva. Muito obg.

**Comment by pallomabritoGN** [comment]
Olá @josearthur ! Tudo bem?
Verificamos que em seu checkout foi removido o campo telefone exibido pelo próprio WooCommerce. Ele é obrigatório para os pagamentos via cartão de crédito, e por ser um campo presente no WooCommerce não houve a repetição do campo na área do checkout responsável pelo nosso plugin. Vale ressaltar que nós utilizamos o campo de telefone que o próprio Woocommerce fornece, podendo ser utilizado sem o Brazilian Market on Woocommerce. Logo, ele precisa estar disponível na hora do checkout.
Qualquer dúvidas estamos à disposição.
