### ISSUE TITLE
Bug no checkout com cartão de crédito

### ISSUE THREAD

**Issue by djmarcosban** [gerencianet/gn-api-woocommerce#44]
Plugin não esta carregando os installments.
A máscara do CPF/CNPJ e Data de Nasc acabam nao funcionando.

--

Também recebo o erro "Uncaught TypeError: document.querySelector(...) is null":
No arquivo gn-payment-token.js precisei retirar o ">" depois de #order_review para conseguir encontrar a tag bdi ficando assim:
let total = document.querySelector(#order_review  table > tfoot > tr.order-total > td > strong > span > bdi)

Uso os plugins Brazilian Market on WooCommerce e Autocomplete Address for WooCommerce.

--

Edit:

Em outro cliente meu, dá esse erro: Uncaught Error: Mismatched anonymous define() module: function

**Comment by jvoliveiraGN** [comment]
Boa tarde @djmarcosban tudo certo?
A falha foi corrigida na versão 2.0.8 :)
Quaisquer dúvidas, conte com a gente!

**Comment by djmarcosban** [comment]
Boa tarde @jvoliveiraGN 
Obrigado pelo feedback.

Instalei a nova versão e as máscaras voltaram a funcionar mas ainda não está buscando os installments. Precisei instalar a versão 1.4.8 novamente.

**Comment by jvoliveiraGN** [comment]
Boa tarde @djmarcosban tudo certo?
Por favor, poderia nos passar mais detalhes pela nossa comunidade do Discord?
Lá conseguimos testar junto com você e identificar o motivo da falha de maneira mais rápida.
https://discord.gg/Yz8A9Fpqss
