### ISSUE TITLE
Conflito com WooCommerce Extra Checkout Fields for Brazil

### ISSUE THREAD

**Issue by iztalo** [gerencianet/gn-api-woocommerce#5]
O maskedinput está conflitando com o mask do WooCommerce Extra Checkout Fields.

/assets/js/jquery.maskedinput.js?ver=4.9.6

Vocês tem previsão de quando poderão solucionar este problema?
Estou perdendo várias vendas.

**Comment by iztalo** [comment]
https://wordpress.org/support/topic/ao-habilitar-mascara-nao-se-pode-editar/

**Comment by tiagoxpl** [comment]
@iztalo 

Agradeço a sua mensagem. Como sempre, a comunidade WordPress sempre fomentando as questões relacionadas a WooCommerce e ajudando a todos.

Já registrei internamente a questão, inclusive as informações contidas no link que você referenciou, porém, não tenho, neste momento, um prazo exato para te passar. Peço por gentileza que acompanhe nosso [changelog](https://github.com/gerencianet/gn-api-woocommerce/blob/master/CHANGELOG.md). Será a melhor forma de acompanhar esta tratativa.

Novamente, obrigado por reportar e, claro, por indagar caminhos para a solução.

À disposição.

**Comment by iztalo** [comment]
Poxa pessoal, decepcionante. Meu contrato me pede para cumprir um X de faturamento por mês mas não posso utilizar o plugin. Complicado.

**Comment by tiagoxpl** [comment]
@iztalo 

Entendo seu ponto de vista, mas não mencionei que já foi repassado internamente e que será tratado? Existem procedimentos que devem ser seguidos, desde o planejamento, execução, testes, homologação, etc.

**Comment by iztalo** [comment]
Não é ponto de vista. Vocês planejam por 14 dias atualizar o script de máscara que é obsoleto? Eita, complicado! Só queria dizer que eu e vocês estão perdendo com isso. Aliás, "vocês" não, o dono da empresa.

**Comment by tiagoxpl** [comment]
@iztalo 

Entendo suas considerações. Inseri todas as informações na demanda interna para atualização do componente, fique tranquilo, será realizado o mais breve possível. Volto a reafirmar que não tenho, neste momento, um prazo exato para te passar.

Qualquer coisa, estamos à disposição.

**Comment by iztalo** [comment]
Boa noite, Tiago. Alguma novidade? Meu contrato com o Gerencianet exigia uma quantidade de vendas por mês no boleto e não estou conseguindo usar o plugin ainda por culpa deste problema.
