### ISSUE TITLE
Atualização do plugin no repositório WordPress

### ISSUE THREAD

**Issue by marcos-alexandre82** [gerencianet/gn-api-woocommerce#9]
Olá, tudo bem?

Alguma previsão de atualizarem o plugin no repositório oficial do WordPress?

https://wordpress.org/plugins/woo-gerencianet-official/

:)

**Comment by jvoliveira** [comment]
Oi @marcos-alexandre82 ! Tudo bem?
A atualização do repositório oficial deve acontecer nos próximos dias! (Acredito que hoje)
Entretanto, a nova versão já está disponível aqui no Github!
Incluindo pagamentos com pix!
Quaisquer dúvidas, estamos à disposição!
:)

**Comment by paulodbs** [comment]
Olá, fiz upload do plugin atualizado porem acho que está com bug, pós chega na finalização do pedido a hora de escolher pix, cartão etc.. não da para selecionar é nem finalizar o pedido o botão fica desabilitado

**Comment by jvoliveiraGN** [comment]
Oi pessoal, desculpe a demora! O plugin já foi atualizado no repositório do Wordpress!
@paulodbs respondi na outra issue 😄
